### ISSUE TITLE
[Feature request] support callback

### ISSUE THREAD

**Issue by xitec-plutokit** [mdit-vue/mdit-vue#10]
### Clear and concise description of the problem

The plugin does not appear to support the original callback option

### Suggested solution

please consider supporting 'callback'  option, because it is more flexible; Thank you very much

**Comment by xitec-plutokit** [comment]
I want to render toc in the sidebar instead of controlling it through position; Because I have something else to render in the sidebar;  fixed position does not solve the problem of rendering toc and normal content in the sidebar at the same time (e.g. top 5 ); If you have any ideas or suggestions, please let me know. thank you

**Comment by meteorlxy** [comment]
If you want to develop a component, I'd suggest you to make use of the `plugin-headers`, which will extract all headers info for you

**Comment by xitec-plutokit** [comment]
thanks
