### ISSUE TITLE
[Feature request] Remove `<h1>` from output after extraction with `plugin-title`

### ISSUE THREAD

**Issue by mrleblanc101** [mdit-vue/mdit-vue#11]
### Clear and concise description of the problem

I use the `env.title` in a custom page header, which is not in the same output as the rest of the content.
Currently, this leads to a duplicated `<h1>`, one from my header and one from the content.

### Suggested solution

It would be nice to have a way to automatically remove it from the output.
This could be an option, and probably disabled by default. Ex: `extractFromOutput: true`

### Alternative

Chain a custom markdown-it plugin that does only this.
But I haven't figured out how to do this yet.

**Comment by meteorlxy** [comment]
Interesting use case. Why don't you consider using `title` frontmatter instead?

**Comment by mrleblanc101** [comment]
I do not have control of the source

**Comment by meteorlxy** [comment]
@mrleblanc101 I think it's out of the scope of `plugin-title`. To can create a similar custom mdit plugin to remove the h1 token from `tokens`:

https://github.com/mdit-vue/mdit-vue/blob/f3a9ce7a58c71d3dcea09797ecd66fe9d6d226b7/packages/plugin-title/src/title-plugin.ts#L13-L23

**Comment by mrleblanc101** [comment]
I think it makes perfect sense for this plugin to have an option to extract instead of "copy".
I'm not a markdown-it expert, can't say the doc to create  is very clear (it barely mention anything about plugins).
I got it working but I have no idea how clean or optimal this is:
```js
export default function (md, opts) {
    if (!opts) return;
    if (!opts.extractTitle) return;

    const proxy = (tokens, idx, options, env, self) => self.renderToken(tokens, idx, options);
    const defaultHeadingOpenRenderer = md.renderer.rules['heading_open'] || proxy;
    const defaultHeadingCloseRenderer = md.renderer.rules['heading_close'] || proxy;
    md.renderer.rules['heading_open'] = function (tokens, idx, options, env, self) {
        let removed = false;
        if (tokens[idx].tag === 'h1' && !removed) {
            tokens[idx].hidden = true;
            tokens[idx + 1].hidden = true;
            tokens[idx + 1].children = [];
            tokens[idx + 2].hidden = true;
            removed = true;
        }
        return defaultHeadingOpenRenderer(tokens, idx, options, env, self);
    };
    md.renderer.rules['heading_close'] = function (tokens, idx, options, env, self) {
        if (tokens[idx].tag === 'h1') {
            tokens[idx].hidden = true;
        }
        return defaultHeadingCloseRenderer(tokens, idx, options, env, self);
    };
}
```
