### ISSUE TITLE
[Feature request] [plugin-toc] Allow toggling headers in nested blocks

### ISSUE THREAD

**Issue by brc-dd** [mdit-vue/mdit-vue#5]
Hi, can this change be made toggleable - https://github.com/mdit-vue/mdit-vue/commit/ce146bdb3f3c84320a9f7a0a4fac6f3f67bd67f8. Seems like some people expect toc/headers to render content of blockquotes too.

### Suggested solution

Maybe a new option like `headers.allowNested`?

**Comment by meteorlxy** [comment]
Hi, @brc-dd sorry for delay. Any referenced issue for that? Thanks!

cc @mister-hope

**Comment by brc-dd** [comment]
@meteorlxy It's on [#vitepress discord channel](https://discord.com/channels/325477692906536972/790509637598314527/1062777677783769158).

**Comment by Mister-Hope** [comment]
I think an option could be better. However I still disagree that headings in blockquote should be extracted.

When you use blockquote, it means you are trying to reference something, and you are quoting a piece of document, so any headers should not be extracted.

**Comment by staghouse** [comment]
> I think an option could be better. However I still disagree that headings in blockquote should be extracted.
> 
> When you use blockquote, it means you are trying to reference something, and you are quoting a piece of document, so any headers should not be extracted.

While I understand this concept, in Vitepress, for my documentation of fields related to a data model, I like to blockquote them to enable styling to the elements as opposed to writing HTML in the markdown file. This separates out the content to be styled logically if that makes sense while also keeping my MD linter from complaining about unnecessary HTML in my MD
