### ISSUE TITLE
[Feature request] Create a VSCode plugin

### ISSUE THREAD

**Issue by pomdtr** [mdit-vue/mdit-vue#6]
### Clear and concise description of the problem

The development experience of vitepress website could be better in vscode the markdown-it extensions were handled by the markdown preview.

### Suggested solution

It looks like vscode supports markdown-it plugins, so it might be quite easy to add a VitePress powered preview.

### Alternative

Use vscode `simpleBrowser.api.open` command to show the development server.

**Comment by meteorlxy** [comment]
Yeah, that might be possible, but should be out of the scope of this project. VitePress also has its own extra extensions for markdown-it. This project only holds some basic ones.
